/**
 * Holds constant values for Case defaults and error types.
 * Used to avoid hardcoding strings across the org.
 */
public class ApexConstants {
    // Case Object
    public static final String CASE_STATUS_NEW = 'New';
    public static final String CASE_ORIGIN_WEB = 'Web';
    public static final String CASE_ORIGIN_MOBILE = 'Mobile';

    // Error Logger - Error Types
    public static final string ERROR_TYPE_API = 'API';
    public static final string ERROR_TYPE_APEX_TRIGGER = 'Trigger';
}